// Espejo de los PermissionKey del backend. Mantener sincronizado con el seed.
export type Permission =
  | 'users.read'
  | 'users.create'
  | 'users.update'
  | 'users.deactivate'
  | 'roles.read'
  | 'roles.manage'
  | 'patients.read'
  | 'patients.create'
  | 'patients.update'
  | 'patients.deactivate'
  | 'records.read'
  | 'records.create'
  | 'records.correct'
  | 'records.void'
  | 'documents.upload'
  | 'documents.read'
  | 'documents.validate'
  | 'documents.reject'
  | 'entities.read'
  | 'entities.validate'
  | 'review.read'
  | 'review.assign'
  | 'admin.users.manage'
  | 'admin.roles.manage'
  | 'admin.metrics.read'
  | 'admin.audit.read';
