/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check del backend */
        get: operations["AppController_getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar todos los usuarios del sistema */
        get: operations["UsersController_findAll"];
        put?: never;
        /** Crear usuario del sistema (personal de salud o administrador) */
        post: operations["UsersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener usuario por ID */
        get: operations["UsersController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Actualizar perfil profesional o contraseña del usuario */
        patch: operations["UsersController_update"];
        trace?: never;
    };
    "/api/users/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Desactivar usuario (borrado lógico — el registro se conserva para auditoría) */
        patch: operations["UsersController_deactivate"];
        trace?: never;
    };
    "/api/users/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Asignar o reemplazar el rol de un usuario */
        patch: operations["UsersController_assignRole"];
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener la ficha del usuario autenticado */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Iniciar sesión — obtener access token y refresh token */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renovar access token usando el refresh token */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cerrar sesión — revocar el refresh token activo */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar todos los roles con sus permisos */
        get: operations["RolesController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener un rol por ID con sus permisos */
        get: operations["RolesController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar pacientes activos — con búsqueda por nombre/documento y paginación */
        get: operations["PatientsController_findAll"];
        put?: never;
        /** Registrar nuevo paciente */
        post: operations["PatientsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener paciente por ID */
        get: operations["PatientsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Actualizar datos demográficos del paciente */
        patch: operations["PatientsController_update"];
        trace?: never;
    };
    "/api/patients/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Desactivar paciente (borrado lógico) */
        patch: operations["PatientsController_deactivate"];
        trace?: never;
    };
    "/api/patients/{patientId}/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar historias clínicas de un paciente */
        get: operations["ClinicalRecordsController_findAll"];
        put?: never;
        /** Crear historia clínica para un paciente */
        post: operations["ClinicalRecordsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{patientId}/records/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener una historia clínica por ID */
        get: operations["ClinicalRecordsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{patientId}/records/{id}/correct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Emitir corrección sobre una historia clínica activa */
        post: operations["ClinicalRecordsController_correct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{patientId}/records/{id}/void": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Anular una historia clínica activa */
        patch: operations["ClinicalRecordsController_void"];
        trace?: never;
    };
    "/api/patients/{patientId}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar documentos de un paciente */
        get: operations["MedicalDocumentsController_findAll"];
        put?: never;
        /** Subir documento medico (PDF, JPEG, PNG; maximo configurable por UPLOAD_MAX_SIZE_MB) */
        post: operations["MedicalDocumentsController_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{patientId}/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener metadatos de un documento */
        get: operations["MedicalDocumentsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{patientId}/documents/{id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Descargar / visualizar el archivo del documento */
        get: operations["MedicalDocumentsController_downloadFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{patientId}/documents/{id}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enviar documento al worker de OCR/NER */
        post: operations["MedicalDocumentsController_process"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{patientId}/documents/{id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Validar documento procesado (revisiÃ³n clÃ­nica) */
        patch: operations["MedicalDocumentsController_validate"];
        trace?: never;
    };
    "/api/patients/{patientId}/documents/{id}/correction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Guardar correccion de OCR/entidades sin sobrescribir el original */
        patch: operations["MedicalDocumentsController_saveCorrection"];
        trace?: never;
    };
    "/api/patients/{patientId}/documents/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rechazar documento (con motivo) */
        patch: operations["MedicalDocumentsController_reject"];
        trace?: never;
    };
    "/api/review/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cola de revisión — documentos procesados pendientes de validación clínica */
        get: operations["ReviewController_getQueue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateUserDto: {
            /**
             * @description Nombres del profesional.
             * @example María
             */
            firstName: string;
            /**
             * @description Apellidos del profesional.
             * @example López Sánchez
             */
            lastName: string;
            /**
             * @description Email institucional único del usuario.
             * @example maria.lopez@hospital.org
             */
            email: string;
            /**
             * @description Nombre de usuario único para identificación interna.
             * @example mlopez
             */
            username: string;
            /**
             * @description Tipo de documento de identidad del profesional.
             * @example DNI
             * @enum {string}
             */
            documentType?: "DNI" | "CE" | "PAS" | "OTHER";
            /**
             * @description Número de documento de identidad del profesional.
             * @example 12345678
             */
            documentNumber?: string;
            /**
             * @description Profesión o cargo profesional visible en la ficha de usuario.
             * @example Médico pediatra
             */
            profession?: string;
            /**
             * @description Clave del rol inicial. Si se omite, el usuario se crea sin rol asignado.
             * @example MEDICO
             */
            roleKey?: string;
            /** @description Contraseña (mínimo 8 caracteres). No se devuelve en ninguna respuesta. */
            password: string;
        };
        UserRoleSummaryDto: {
            key: string;
            name: string;
        };
        UserResponseDto: {
            /**
             * Format: uuid
             * @example c7f3a1b2-...
             */
            id: string;
            /** @example maria.lopez@hospital.org */
            email: string;
            /** @example mlopez */
            username: string;
            /** @example María */
            firstName: string;
            /** @example López Sánchez */
            lastName: string;
            /** @example María López */
            fullName: string;
            /** @enum {string|null} */
            documentType?: "DNI" | "CE" | "PAS" | "OTHER" | null;
            /** @example 12345678 */
            documentNumber?: string | null;
            /** @example Médico pediatra */
            profession?: string | null;
            /** @description false si el usuario fue desactivado (borrado lógico). */
            isActive: boolean;
            /** Format: date-time */
            lastLoginAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            roles: components["schemas"]["UserRoleSummaryDto"][];
        };
        UpdateUserDto: {
            /**
             * @description Nombres del profesional.
             * @example María
             */
            firstName?: string;
            /**
             * @description Apellidos del profesional.
             * @example López Sánchez
             */
            lastName?: string;
            /**
             * @description Nombre de usuario único para identificación interna.
             * @example mlopez
             */
            username?: string;
            /**
             * @description Tipo de documento de identidad del profesional.
             * @example DNI
             * @enum {string}
             */
            documentType?: "DNI" | "CE" | "PAS" | "OTHER";
            /**
             * @description Número de documento de identidad del profesional.
             * @example 12345678
             */
            documentNumber?: string;
            /**
             * @description Profesión o cargo profesional visible en la ficha de usuario.
             * @example Médico pediatra
             */
            profession?: string;
            /** @description Contraseña (mínimo 8 caracteres). No se devuelve en ninguna respuesta. */
            password?: string;
        };
        AssignRoleDto: {
            /**
             * @description Clave del rol a asignar (ej. MEDICO, ADMINISTRADOR).
             * @example MEDICO
             */
            roleKey: string;
        };
        LoginDto: {
            /** @example admin@hospital.org */
            email: string;
            password: string;
        };
        TokenResponseDto: {
            access_token: string;
            refresh_token: string;
            /** @default Bearer */
            token_type: string;
        };
        RefreshDto: {
            refresh_token: string;
        };
        LogoutDto: {
            refresh_token: string;
        };
        PermissionResponseDto: {
            id: string;
            key: string;
            description?: Record<string, never> | null;
        };
        RoleResponseDto: {
            id: string;
            key: string;
            name: string;
            description?: Record<string, never> | null;
            permissions: components["schemas"]["PermissionResponseDto"][];
            /** Format: date-time */
            createdAt: string;
        };
        CreatePatientDto: {
            /**
             * @example DNI
             * @enum {string}
             */
            documentType: "DNI" | "CE" | "PAS" | "OTHER";
            /** @example 12345678 */
            documentNumber: string;
            /** @example María */
            firstName: string;
            /** @example García López */
            lastName: string;
            /**
             * @description Fecha en formato YYYY-MM-DD
             * @example 1985-06-15
             */
            dateOfBirth: string;
            /**
             * @example F
             * @enum {string}
             */
            sex: "M" | "F" | "OTHER";
            /** @example +51 987 654 321 */
            phone?: string;
            /** @example paciente@correo.com */
            email?: string;
            /** @example Av. Principal 123, Lima */
            address?: string;
        };
        PatientResponseDto: {
            id: string;
            /** @enum {string} */
            documentType: "DNI" | "CE" | "PAS" | "OTHER";
            documentNumber: string;
            firstName: string;
            lastName: string;
            /** Format: date-time */
            dateOfBirth: string;
            /** @enum {string} */
            sex: "M" | "F" | "OTHER";
            phone: string | null;
            email: string | null;
            address: string | null;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdatePatientDto: {
            /** @example María */
            firstName?: string;
            /** @example García López */
            lastName?: string;
            /**
             * @description Fecha en formato YYYY-MM-DD
             * @example 1985-06-15
             */
            dateOfBirth?: string;
            /**
             * @example F
             * @enum {string}
             */
            sex?: "M" | "F" | "OTHER";
            /** @example +51 987 654 321 */
            phone?: string;
            /** @example paciente@correo.com */
            email?: string;
            /** @example Av. Principal 123, Lima */
            address?: string;
        };
        CreateRecordDto: {
            /** @enum {string} */
            recordType: "CONSULTATION" | "LAB_RESULT" | "PRESCRIPTION" | "THERAPY_NOTE" | "EVOLUTION" | "PROCEDURE" | "OTHER";
            /**
             * @default MANUAL
             * @enum {string}
             */
            origin: "MANUAL" | "DIGITIZED";
            /** @description Fecha y hora de la atención (ISO 8601) */
            attendedAt: string;
            summary: string;
            notes?: string;
        };
        RecordResponseDto: {
            id: string;
            patientId: string;
            /** @enum {string} */
            recordType: "CONSULTATION" | "LAB_RESULT" | "PRESCRIPTION" | "THERAPY_NOTE" | "EVOLUTION" | "PROCEDURE" | "OTHER";
            /** @enum {string} */
            origin: "MANUAL" | "DIGITIZED";
            /** @enum {string} */
            status: "ACTIVE" | "CORRECTED" | "VOIDED";
            /** Format: date-time */
            attendedAt: string;
            summary: string;
            notes?: string | null;
            parentRecordId?: string | null;
            voidReason?: string | null;
            correctionsCount: number;
            /** Format: date-time */
            createdAt: string;
            createdBy?: string | null;
            /** Format: date-time */
            updatedAt: string;
        };
        CorrectRecordDto: {
            /** @description Nueva fecha de atención (hereda la original si se omite) */
            attendedAt?: string;
            summary: string;
            notes?: string;
        };
        VoidRecordDto: {
            /** @description Motivo de anulación */
            reason: string;
        };
        DocumentResponseDto: {
            id: string;
            patientId: string;
            originalName: string;
            mimeType: string;
            sizeBytes: number;
            /** @enum {string} */
            status: "PENDING" | "PROCESSING" | "PROCESSED" | "FAILED" | "VALIDATED" | "REJECTED";
            ocrText?: string | null;
            nerEntities?: {
                /** @enum {string} */
                type?: "DIAGNOSIS" | "SYMPTOM" | "MEDICATION" | "PROCEDURE" | "CLINICAL_DATE" | "OBSERVATION";
                value?: string;
                normalizedValue?: string | null;
                sourceSpan?: {
                    page?: number;
                    start?: number;
                    end?: number;
                } | null;
                confidence?: number;
            }[] | null;
            correctedText?: string | null;
            correctedEntities?: {
                /** @enum {string} */
                type?: "DIAGNOSIS" | "SYMPTOM" | "MEDICATION" | "PROCEDURE" | "CLINICAL_DATE" | "OBSERVATION";
                value?: string;
                normalizedValue?: string | null;
            }[] | null;
            correctedAt?: string | null;
            correctedById?: string | null;
            rejectReason?: string | null;
            /** Format: date-time */
            createdAt: string;
            createdBy?: string | null;
            processedAt?: string | null;
            reviewedAt?: string | null;
            reviewedBy?: string | null;
            /** Format: date-time */
            updatedAt: string;
        };
        CorrectedEntityDto: {
            /** @enum {string} */
            type?: "DIAGNOSIS" | "SYMPTOM" | "MEDICATION" | "PROCEDURE" | "CLINICAL_DATE" | "OBSERVATION";
            value?: string;
            normalizedValue?: Record<string, never> | null;
        };
        CorrectDocumentDto: {
            /** @description Texto corregido por el revisor. No sobrescribe el OCR original. */
            correctedText?: string;
            correctedEntities?: components["schemas"]["CorrectedEntityDto"][];
        };
        RejectDocumentDto: {
            /** @description Motivo del rechazo */
            reason: string;
        };
        ReviewPatientSummaryDto: {
            id: string;
            firstName: string;
            lastName: string;
            documentType: string;
            documentNumber: string;
        };
        ReviewQueueItemDto: {
            id: string;
            originalName: string;
            mimeType: string;
            sizeBytes: number;
            processedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            patient: components["schemas"]["ReviewPatientSummaryDto"];
        };
        ReviewQueuePageDto: {
            data: components["schemas"]["ReviewQueueItemDto"][];
            total: number;
            page: number;
            limit: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"][];
                };
            };
        };
    };
    UsersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            /** @description Usuario creado correctamente. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description El email ya está registrado en el sistema. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description Usuario no encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description Usuario no encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description Usuario no encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_assignRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignRoleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description Usuario o rol no encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description Access token inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponseDto"];
                };
            };
            /** @description Credenciales inválidas. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponseDto"];
                };
            };
            /** @description Refresh token inválido, expirado o revocado. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutDto"];
            };
        };
        responses: {
            /** @description Sesión cerrada. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Access token inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleResponseDto"][];
                };
            };
        };
    };
    RolesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleResponseDto"];
                };
            };
            /** @description Rol no encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PatientsController_findAll: {
        parameters: {
            query?: {
                /** @description Texto libre — busca en nombre y número de documento */
                search?: string;
                documentType?: "DNI" | "CE" | "PAS" | "OTHER";
                documentNumber?: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PatientsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePatientDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientResponseDto"];
                };
            };
            /** @description Ya existe un paciente con ese tipo y número de documento. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PatientsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientResponseDto"];
                };
            };
            /** @description Paciente no encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PatientsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePatientDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientResponseDto"];
                };
            };
            /** @description Paciente no encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PatientsController_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientResponseDto"];
                };
            };
            /** @description Paciente no encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClinicalRecordsController_findAll: {
        parameters: {
            query?: {
                recordType?: "CONSULTATION" | "LAB_RESULT" | "PRESCRIPTION" | "THERAPY_NOTE" | "EVOLUTION" | "PROCEDURE" | "OTHER";
                status?: "ACTIVE" | "CORRECTED" | "VOIDED";
                origin?: "MANUAL" | "DIGITIZED";
                /** @description Desde (ISO 8601, inclusivo) */
                from?: string;
                /** @description Hasta (ISO 8601, inclusivo) */
                to?: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClinicalRecordsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRecordDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordResponseDto"];
                };
            };
        };
    };
    ClinicalRecordsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordResponseDto"];
                };
            };
        };
    };
    ClinicalRecordsController_correct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectRecordDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordResponseDto"];
                };
            };
        };
    };
    ClinicalRecordsController_void: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoidRecordDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordResponseDto"];
                };
            };
        };
    };
    MedicalDocumentsController_findAll: {
        parameters: {
            query?: {
                status?: "PENDING" | "PROCESSING" | "PROCESSED" | "FAILED" | "VALIDATED" | "REJECTED";
                page?: number;
                limit?: number;
            };
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MedicalDocumentsController_upload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponseDto"];
                };
            };
        };
    };
    MedicalDocumentsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponseDto"];
                };
            };
        };
    };
    MedicalDocumentsController_downloadFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MedicalDocumentsController_process: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponseDto"];
                };
            };
        };
    };
    MedicalDocumentsController_validate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponseDto"];
                };
            };
        };
    };
    MedicalDocumentsController_saveCorrection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectDocumentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponseDto"];
                };
            };
        };
    };
    MedicalDocumentsController_reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectDocumentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponseDto"];
                };
            };
        };
    };
    ReviewController_getQueue: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewQueuePageDto"];
                };
            };
        };
    };
}
