/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check del backend */
        get: operations["AppController_getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar eventos técnicos de auditoría append-only */
        get: operations["AuditController_findMany"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar todos los usuarios del sistema */
        get: operations["UsersController_findAll"];
        put?: never;
        /** Crear usuario del sistema (personal de salud o administrador) */
        post: operations["UsersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/professionals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar profesionales activos (nombre/profesión) — para selectores clínicos, sin datos sensibles */
        get: operations["UsersController_searchProfessionals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener usuario por ID */
        get: operations["UsersController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Actualizar perfil profesional o contraseña del usuario */
        patch: operations["UsersController_update"];
        trace?: never;
    };
    "/api/users/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Desactivar usuario (borrado lógico — el registro se conserva para auditoría) */
        patch: operations["UsersController_deactivate"];
        trace?: never;
    };
    "/api/users/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Asignar o reemplazar el rol de un usuario */
        patch: operations["UsersController_assignRole"];
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener la ficha del usuario autenticado */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Iniciar sesión y establecer un refresh token HttpOnly */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotar la cookie HttpOnly y renovar el access token */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revocar la sesión actual y borrar la cookie HttpOnly */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar todos los roles con sus permisos */
        get: operations["RolesController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener un rol por ID con sus permisos */
        get: operations["RolesController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar pacientes activos — con búsqueda por nombre/documento y paginación */
        get: operations["PatientsController_findAll"];
        put?: never;
        /** Registrar nuevo paciente */
        post: operations["PatientsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/draft/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener el borrador privado vigente del alta de paciente */
        get: operations["PatientsController_getCurrentRegistrationDraft"];
        /** Crear o reemplazar mediante CAS el borrador privado del alta */
        put: operations["PatientsController_upsertCurrentRegistrationDraft"];
        post?: never;
        /** Eliminar mediante CAS el borrador privado del alta */
        delete: operations["PatientsController_deleteCurrentRegistrationDraft"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Indicadores de la lista de pacientes (total, activos, nuevos, con documentos) */
        get: operations["PatientsController_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{id}/clinical-history/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener la historia clínica completa para exportación
         * @description Devuelve todos los registros, incluidos corregidos y anulados, y todos los documentos con su estado. El texto de documentos no validados se omite.
         */
        get: operations["PatientsController_exportClinicalHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener paciente por ID */
        get: operations["PatientsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Actualizar datos demográficos del paciente */
        patch: operations["PatientsController_update"];
        trace?: never;
    };
    "/api/patients/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Desactivar paciente (borrado lógico) */
        patch: operations["PatientsController_deactivate"];
        trace?: never;
    };
    "/api/patients/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Reactivar paciente desactivado */
        patch: operations["PatientsController_activate"];
        trace?: never;
    };
    "/api/patients/{patientId}/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar historias clínicas de un paciente */
        get: operations["ClinicalRecordsController_findAll"];
        put?: never;
        /** Crear historia clínica para un paciente */
        post: operations["ClinicalRecordsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{patientId}/records/draft/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener el borrador clínico vigente del usuario para el paciente */
        get: operations["ClinicalRecordsController_getCurrentDraft"];
        /** Crear o reemplazar con CAS el borrador clínico vigente */
        put: operations["ClinicalRecordsController_upsertCurrentDraft"];
        post?: never;
        /** Eliminar con CAS el borrador clínico vigente */
        delete: operations["ClinicalRecordsController_deleteCurrentDraft"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{patientId}/records/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener una historia clínica por ID */
        get: operations["ClinicalRecordsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{patientId}/records/{id}/correct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Emitir corrección sobre una historia clínica activa */
        post: operations["ClinicalRecordsController_correct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{patientId}/records/{id}/void": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Anular una historia clínica activa */
        patch: operations["ClinicalRecordsController_void"];
        trace?: never;
    };
    "/api/patients/{patientId}/record-media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Subir y normalizar una imagen clínica temporal privada */
        post: operations["ClinicalRecordMediaController_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{patientId}/record-media/{assetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener metadata segura de una imagen clínica */
        get: operations["ClinicalRecordMediaController_getMetadata"];
        put?: never;
        post?: never;
        /** Eliminar con CAS una imagen temporal propia */
        delete: operations["ClinicalRecordMediaController_deleteTemporary"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{patientId}/record-media/{assetId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Visualizar el contenido privado de una imagen clínica */
        get: operations["ClinicalRecordMediaController_getContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Indicadores del panel: pacientes hoy, cola, listos para validar, errores OCR y actividad reciente
         * @description Incluye datos identificables de pacientes y actividad documental. Requiere simultáneamente patients.read y documents.read.
         */
        get: operations["DashboardController_getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{patientId}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar documentos de un paciente */
        get: operations["MedicalDocumentsController_findAll"];
        put?: never;
        /** Subir documento medico (PDF, JPEG, PNG; maximo configurable por UPLOAD_MAX_SIZE_MB) */
        post: operations["MedicalDocumentsController_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{patientId}/documents/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar por palabra clave en el texto OCR/corregido de los documentos del paciente */
        get: operations["MedicalDocumentsController_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{patientId}/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener metadatos de un documento */
        get: operations["MedicalDocumentsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{patientId}/documents/{id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Descargar / visualizar el archivo del documento */
        get: operations["MedicalDocumentsController_downloadFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{patientId}/documents/{id}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enviar documento al worker de OCR/NER */
        post: operations["MedicalDocumentsController_process"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{patientId}/documents/{id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Guardar la versión final y validar el documento atómicamente */
        patch: operations["MedicalDocumentsController_validate"];
        trace?: never;
    };
    "/api/patients/{patientId}/documents/{id}/correction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Guardar correccion de OCR/entidades sin sobrescribir el original */
        patch: operations["MedicalDocumentsController_saveCorrection"];
        trace?: never;
    };
    "/api/patients/{patientId}/documents/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rechazar documento (con motivo) */
        patch: operations["MedicalDocumentsController_reject"];
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar mis notificaciones (últimas 20) con contador de no leídas */
        get: operations["NotificationsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Marcar todas mis notificaciones como leídas */
        patch: operations["NotificationsController_markAllRead"];
        trace?: never;
    };
    "/api/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Marcar una notificación como leída */
        patch: operations["NotificationsController_markRead"];
        trace?: never;
    };
    "/api/review/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cola de revisión — documentos procesados pendientes de validación clínica */
        get: operations["ReviewController_getQueue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuditEventResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            occurredAt: string;
            action: string;
            /** @enum {string} */
            outcome: "SUCCESS" | "DENIED" | "FAILED";
            /** Format: uuid */
            actorId?: string | null;
            /** Format: uuid */
            patientId?: string | null;
            resourceType?: string | null;
            /** Format: uuid */
            resourceId?: string | null;
            /** Format: uuid */
            requestId: string;
            method: string;
            route: string;
            statusCode: number;
            durationMs: number;
            ipHash?: string | null;
            userAgentHash?: string | null;
        };
        AuditEventsPageDto: {
            data: components["schemas"]["AuditEventResponseDto"][];
            /** Format: uuid */
            nextCursor?: string | null;
        };
        CreateUserDto: {
            /**
             * @description Nombres del profesional.
             * @example María
             */
            firstName: string;
            /**
             * @description Apellidos del profesional.
             * @example López Sánchez
             */
            lastName: string;
            /**
             * @description Email institucional único del usuario.
             * @example maria.lopez@hospital.org
             */
            email: string;
            /**
             * @description Nombre de usuario único para identificación interna.
             * @example mlopez
             */
            username: string;
            /**
             * @description Tipo de documento de identidad del profesional.
             * @example DNI
             * @enum {string}
             */
            documentType?: "DNI" | "CE" | "PAS" | "OTHER";
            /**
             * @description Número de documento de identidad del profesional.
             * @example 12345678
             */
            documentNumber?: string;
            /**
             * @description Profesión o cargo profesional visible en la ficha de usuario.
             * @example Médico pediatra
             */
            profession?: string;
            /**
             * @description Clave del rol inicial. Si se omite, el usuario se crea sin rol asignado.
             * @example MEDICO
             */
            roleKey?: string;
            /** @description Contraseña (mínimo 8 caracteres). No se devuelve en ninguna respuesta. */
            password: string;
        };
        UserRoleSummaryDto: {
            key: string;
            name: string;
        };
        UserResponseDto: {
            /**
             * Format: uuid
             * @example c7f3a1b2-...
             */
            id: string;
            /** @example maria.lopez@hospital.org */
            email: string;
            /** @example mlopez */
            username: string;
            /** @example María */
            firstName: string;
            /** @example López Sánchez */
            lastName: string;
            /** @example María López */
            fullName: string;
            /** @enum {string|null} */
            documentType?: "DNI" | "CE" | "PAS" | "OTHER" | null;
            /** @example 12345678 */
            documentNumber?: string | null;
            /** @example Médico pediatra */
            profession?: string | null;
            /** @description false si el usuario fue desactivado (borrado lógico). */
            isActive: boolean;
            /** Format: date-time */
            lastLoginAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            roles: components["schemas"]["UserRoleSummaryDto"][];
        };
        UpdateUserDto: {
            /**
             * @description Nombres del profesional.
             * @example María
             */
            firstName?: string;
            /**
             * @description Apellidos del profesional.
             * @example López Sánchez
             */
            lastName?: string;
            /**
             * @description Nombre de usuario único para identificación interna.
             * @example mlopez
             */
            username?: string;
            /**
             * @description Tipo de documento de identidad del profesional.
             * @example DNI
             * @enum {string}
             */
            documentType?: "DNI" | "CE" | "PAS" | "OTHER";
            /**
             * @description Número de documento de identidad del profesional.
             * @example 12345678
             */
            documentNumber?: string;
            /**
             * @description Profesión o cargo profesional visible en la ficha de usuario.
             * @example Médico pediatra
             */
            profession?: string;
            /** @description Contraseña (mínimo 8 caracteres). No se devuelve en ninguna respuesta. */
            password?: string;
        };
        AssignRoleDto: {
            /**
             * @description Clave del rol a asignar (ej. MEDICO, ADMINISTRADOR).
             * @example MEDICO
             */
            roleKey: string;
        };
        LoginDto: {
            /** @example admin@hospital.org */
            email: string;
            password: string;
            /**
             * @description Mantiene la cookie de sesión después de cerrar el navegador.
             * @default false
             */
            rememberMe: boolean;
        };
        TokenResponseDto: {
            access_token: string;
            /** @default Bearer */
            token_type: string;
            /**
             * @description Vigencia del access token en segundos.
             * @example 900
             */
            expires_in: number;
        };
        PermissionResponseDto: {
            id: string;
            key: string;
            description?: Record<string, never> | null;
        };
        RoleResponseDto: {
            id: string;
            key: string;
            name: string;
            description?: Record<string, never> | null;
            permissions: components["schemas"]["PermissionResponseDto"][];
            /** Format: date-time */
            createdAt: string;
        };
        CreatePatientDto: {
            /**
             * @example DNI
             * @enum {string}
             */
            documentType: "DNI" | "CE" | "PAS" | "OTHER";
            /** @example 12345678 */
            documentNumber: string;
            /** @example María */
            firstName: string;
            /** @example García López */
            lastName: string;
            /**
             * Format: date
             * @description Fecha civil en formato YYYY-MM-DD; no puede estar en el futuro en Lima
             * @example 1985-06-15
             */
            dateOfBirth: string;
            /**
             * @example F
             * @enum {string}
             */
            sex: "M" | "F" | "OTHER";
            /** @example +51 987 654 321 */
            phone?: string;
            /** @example paciente@correo.com */
            email?: string;
            /** @example Av. Principal 123, Lima */
            address?: string;
            /**
             * Format: uuid
             * @description Borrador privado que se consumirá atómicamente con el alta.
             */
            draftId?: string;
            /** @description Versión observada del borrador que se consumirá. */
            expectedDraftVersion?: number;
        };
        PatientResponseDto: {
            id: string;
            /** @enum {string} */
            documentType: "DNI" | "CE" | "PAS" | "OTHER";
            documentNumber: string;
            firstName: string;
            lastName: string;
            /**
             * Format: date
             * @example 1985-06-15
             */
            dateOfBirth: string;
            /** @enum {string} */
            sex: "M" | "F" | "OTHER";
            phone: string | null;
            email: string | null;
            address: string | null;
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PatientRegistrationDraftPayloadDto: {
            /** @enum {string} */
            documentType?: "DNI" | "CE" | "PAS" | "OTHER";
            documentNumber?: string;
            firstName?: string;
            lastName?: string;
            /** Format: date */
            dateOfBirth?: string;
            /** @enum {string} */
            sex?: "M" | "F" | "OTHER";
            phone?: string;
            email?: string;
            address?: string;
        };
        PatientRegistrationDraftResponseDto: {
            /** Format: uuid */
            id: string;
            payload: components["schemas"]["PatientRegistrationDraftPayloadDto"];
            version: number;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpsertPatientRegistrationDraftDto: {
            /**
             * Format: uuid
             * @description Identidad del borrador al actualizar. Se omite al crearlo.
             */
            expectedId?: string;
            /** @description Versión observada del borrador. Se omite al crearlo. */
            expectedVersion?: number;
            payload: components["schemas"]["PatientRegistrationDraftPayloadDto"];
        };
        ClinicalHistoryExportPatientDto: {
            id: string;
            /** @enum {string} */
            documentType: "DNI" | "CE" | "PAS" | "OTHER";
            documentNumber: string;
            firstName: string;
            lastName: string;
            /**
             * Format: date
             * @example 1985-06-15
             */
            dateOfBirth: string;
            /** @enum {string} */
            sex: "M" | "F" | "OTHER";
            phone?: string | null;
            email?: string | null;
            address?: string | null;
        };
        ClinicalMediaAssetResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            patientId: string;
            originalName: string;
            /** @enum {string} */
            mimeType: "image/jpeg" | "image/png";
            sizeBytes: number;
            width: number;
            height: number;
            sha256: string;
            /** @enum {string} */
            status: "TEMPORARY" | "ATTACHED";
            /** Format: date-time */
            expiresAt?: string | null;
            version: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** @example /patients/:patientId/record-media/:assetId/content */
            contentUrl: string;
        };
        ClinicalRecordAttachmentResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            assetId: string;
            sectionKey?: string | null;
            caption?: string | null;
            altText?: string | null;
            sortOrder: number;
            /** Format: uuid */
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
            asset: components["schemas"]["ClinicalMediaAssetResponseDto"];
        };
        ClinicalHistoryExportRecordDto: {
            id: string;
            /** @enum {string} */
            recordType: "CONSULTATION" | "LAB_RESULT" | "PRESCRIPTION" | "THERAPY_NOTE" | "EVOLUTION" | "PROCEDURE" | "OTHER";
            /** @enum {string} */
            origin: "MANUAL" | "DIGITIZED";
            /** @enum {string} */
            status: "ACTIVE" | "CORRECTED" | "VOIDED";
            /** Format: date-time */
            attendedAt: string;
            summary: string;
            notes?: string | null;
            /** @description Contenido clínico tipado según recordType y schemaVersion. */
            details: Record<string, never>;
            schemaVersion: number;
            doctorName?: string | null;
            /** Format: uuid */
            professionalId?: string | null;
            professionalNameSnapshot?: string | null;
            professionalLicenseSnapshot?: string | null;
            service?: string | null;
            preliminaryDiagnosis?: string | null;
            plan?: string | null;
            /** @enum {string} */
            priority: "URGENT" | "PRIORITY" | "NORMAL" | "ELECTIVE";
            parentRecordId?: string | null;
            voidReason?: string | null;
            /** Format: date-time */
            createdAt: string;
            createdBy?: string | null;
            /** Format: date-time */
            updatedAt: string;
            updatedBy?: string | null;
            version: number;
            attachments: components["schemas"]["ClinicalRecordAttachmentResponseDto"][];
        };
        ClinicalHistoryExportDocumentDto: {
            id: string;
            originalName: string;
            mimeType: string;
            sizeBytes: number;
            /** @enum {string} */
            status: "PENDING" | "PROCESSING" | "PROCESSED" | "FAILED" | "VALIDATED" | "REJECTED";
            /** @description Texto clínico consolidado. Solo se expone cuando el documento fue validado. */
            clinicalText?: string | null;
            /** @enum {string} */
            textSource: "CORRECTED" | "OCR" | "NONE";
            rejectReason?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            processedAt?: string | null;
            /** Format: date-time */
            correctedAt?: string | null;
            correctedById?: string | null;
            /** Format: date-time */
            reviewedAt?: string | null;
            reviewedBy?: string | null;
            validationChecklist?: Record<string, never> | null;
            /** Format: date-time */
            validationAttestedAt?: string | null;
            createdBy?: string | null;
            updatedBy?: string | null;
        };
        ClinicalHistoryExportResponseDto: {
            patient: components["schemas"]["ClinicalHistoryExportPatientDto"];
            records: components["schemas"]["ClinicalHistoryExportRecordDto"][];
            documents: components["schemas"]["ClinicalHistoryExportDocumentDto"][];
            /**
             * Format: date-time
             * @description Instante del servidor en que se generó la instantánea para la exportación.
             */
            generatedAt: string;
        };
        UpdatePatientDto: {
            /** @example María */
            firstName?: string;
            /** @example García López */
            lastName?: string;
            /**
             * Format: date
             * @description Fecha civil en formato YYYY-MM-DD; no puede estar en el futuro en Lima
             * @example 1985-06-15
             */
            dateOfBirth?: string;
            /**
             * @example F
             * @enum {string}
             */
            sex?: "M" | "F" | "OTHER";
            /** @example +51 987 654 321 */
            phone?: string;
            /** @example paciente@correo.com */
            email?: string;
            /** @example Av. Principal 123, Lima */
            address?: string;
            /**
             * Format: uuid
             * @description Borrador privado que se consumirá atómicamente con el alta.
             */
            draftId?: string;
            /** @description Versión observada del borrador que se consumirá. */
            expectedDraftVersion?: number;
        };
        ClinicalDiagnosisDto: {
            description: string;
            /** @description Código clínico, por ejemplo CIE-10. */
            code?: string;
            /** @description Sistema del código clínico. */
            codeSystem?: string;
            /** @enum {string} */
            type?: "PRELIMINARY" | "CONFIRMED" | "RULED_OUT";
        };
        VitalSignsDto: {
            systolicBloodPressure?: number;
            diastolicBloodPressure?: number;
            heartRate?: number;
            respiratoryRate?: number;
            temperatureCelsius?: number;
            oxygenSaturation?: number;
            weightKg?: number;
            heightCm?: number;
        };
        ConsultationDetailsV1Dto: {
            chiefComplaint: string;
            presentIllness?: string;
            relevantHistory?: string;
            vitalSigns?: components["schemas"]["VitalSignsDto"];
            physicalExam?: string;
            diagnoses?: components["schemas"]["ClinicalDiagnosisDto"][];
            followUp?: string;
        };
        EvolutionDetailsV1Dto: {
            evolution: string;
            subjective?: string;
            objective?: string;
            assessment?: string;
            treatmentResponse?: string;
            incidents?: string;
            followUp?: string;
        };
        LabResultItemDto: {
            analyte: string;
            /** @description Resultado cuantitativo o cualitativo. */
            value: string;
            unit?: string;
            referenceRange?: string;
            /** @enum {string} */
            flag?: "NORMAL" | "LOW" | "HIGH" | "CRITICAL" | "ABNORMAL";
        };
        LabResultDetailsV1Dto: {
            studyName: string;
            laboratoryName?: string;
            specimen?: string;
            /** Format: date-time */
            collectedAt?: string;
            /** Format: date-time */
            issuedAt?: string;
            results: components["schemas"]["LabResultItemDto"][];
            interpretation?: string;
        };
        PrescriptionMedicationDto: {
            name: string;
            presentation?: string;
            concentration?: string;
            dose: string;
            route: string;
            frequency: string;
            duration: string;
            quantity?: string;
            instructions?: string;
        };
        PrescriptionDetailsV1Dto: {
            indication?: string;
            medications: components["schemas"]["PrescriptionMedicationDto"][];
            /** Format: date */
            validFrom?: string;
            /** Format: date */
            validUntil?: string;
            nonPharmacologicalInstructions?: string;
        };
        ProcedureDetailsV1Dto: {
            procedureName: string;
            indication?: string;
            bodySite?: string;
            /** @enum {string} */
            laterality?: "LEFT" | "RIGHT" | "BILATERAL" | "NOT_APPLICABLE";
            /** @enum {string} */
            consentStatus?: "DOCUMENTED" | "NOT_REQUIRED" | "UNKNOWN";
            technique: string;
            anesthesia?: string;
            findings?: string;
            /** @description Registrar complicaciones o declarar que no hubo. */
            complications: string;
            outcome?: string;
            postProcedureCare?: string;
        };
        TherapyMeasurementDto: {
            name: string;
            value: string;
            unit?: string;
        };
        TherapyNoteDetailsV1Dto: {
            discipline: string;
            sessionNumber?: number;
            goals?: string;
            baselineStatus?: string;
            interventions: string;
            response: string;
            measurements?: components["schemas"]["TherapyMeasurementDto"][];
            homeInstructions?: string;
            /** Format: date-time */
            nextSessionAt?: string;
        };
        OtherDetailsV1Dto: {
            title: string;
            category: string;
            context?: string;
            content: string;
        };
        RecordAttachmentInputDto: {
            /** Format: uuid */
            assetId: string;
            /** @example physicalExam */
            sectionKey?: string;
            caption?: string;
            /** @description Descripción accesible de la imagen clínica. */
            altText?: string;
            sortOrder?: number;
        };
        CreateRecordDto: {
            /** @enum {string} */
            recordType: "CONSULTATION" | "LAB_RESULT" | "PRESCRIPTION" | "THERAPY_NOTE" | "EVOLUTION" | "PROCEDURE" | "OTHER";
            /**
             * Format: date-time
             * @description Fecha y hora de la atención como instante ISO 8601 con zona horaria
             * @example 2026-09-02T09:30:00-05:00
             */
            attendedAt: string;
            summary: string;
            notes?: string;
            /**
             * Format: uuid
             * @description Usuario profesional seleccionado; el servidor conserva una instantánea de identidad.
             */
            professionalId?: string;
            /** @description Colegiatura consignada para la instantánea del registro. */
            professionalLicense?: string;
            /** @description Médico o profesional responsable */
            doctorName?: string;
            /** @description Servicio o especialidad */
            service?: string;
            preliminaryDiagnosis?: string;
            /** @description Indicaciones / plan de manejo */
            plan?: string;
            /**
             * @default NORMAL
             * @enum {string}
             */
            priority: "URGENT" | "PRIORITY" | "NORMAL" | "ELECTIVE";
            /**
             * @default 1
             * @enum {number}
             */
            schemaVersion: 1;
            /** @description El esquema concreto se discrimina mediante recordType; versión soportada: 1. */
            details: components["schemas"]["ConsultationDetailsV1Dto"] | components["schemas"]["EvolutionDetailsV1Dto"] | components["schemas"]["LabResultDetailsV1Dto"] | components["schemas"]["PrescriptionDetailsV1Dto"] | components["schemas"]["ProcedureDetailsV1Dto"] | components["schemas"]["TherapyNoteDetailsV1Dto"] | components["schemas"]["OtherDetailsV1Dto"];
            /** @default [] */
            attachments: components["schemas"]["RecordAttachmentInputDto"][];
            /**
             * Format: uuid
             * @description Borrador del actor que se consumirá atómicamente al crear el registro.
             */
            draftId?: string;
        };
        RecordResponseDto: {
            id: string;
            patientId: string;
            /** @enum {string} */
            recordType: "CONSULTATION" | "LAB_RESULT" | "PRESCRIPTION" | "THERAPY_NOTE" | "EVOLUTION" | "PROCEDURE" | "OTHER";
            /** @enum {string} */
            origin: "MANUAL" | "DIGITIZED";
            /** @enum {string} */
            status: "ACTIVE" | "CORRECTED" | "VOIDED";
            /** Format: date-time */
            attendedAt: string;
            summary: string;
            notes?: string | null;
            /** @description Contenido tipado según recordType y schemaVersion. */
            details: Record<string, never>;
            schemaVersion: number;
            doctorName?: string | null;
            /** Format: uuid */
            professionalId?: string | null;
            professionalNameSnapshot?: string | null;
            professionalLicenseSnapshot?: string | null;
            service?: string | null;
            preliminaryDiagnosis?: string | null;
            plan?: string | null;
            /** @enum {string} */
            priority: "URGENT" | "PRIORITY" | "NORMAL" | "ELECTIVE";
            parentRecordId?: string | null;
            voidReason?: string | null;
            correctionsCount: number;
            /** Format: date-time */
            createdAt: string;
            createdBy?: string | null;
            /** Format: date-time */
            updatedAt: string;
            version: number;
            attachments: components["schemas"]["ClinicalRecordAttachmentResponseDto"][];
        };
        RecordDraftResponseDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            patientId: string;
            payload: Record<string, never>;
            version: number;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        RecordDraftPayloadDto: {
            /** @enum {string} */
            recordType?: "CONSULTATION" | "LAB_RESULT" | "PRESCRIPTION" | "THERAPY_NOTE" | "EVOLUTION" | "PROCEDURE" | "OTHER";
            /** Format: date-time */
            attendedAt?: string;
            summary?: string;
            notes?: string;
            /** Format: uuid */
            professionalId?: string;
            doctorName?: string;
            professionalLicense?: string;
            service?: string;
            preliminaryDiagnosis?: string;
            plan?: string;
            /** @enum {string} */
            priority?: "URGENT" | "PRIORITY" | "NORMAL" | "ELECTIVE";
            /**
             * @default 1
             * @enum {number}
             */
            schemaVersion: 1;
            /** @description El esquema concreto se discrimina mediante recordType; versión soportada: 1. */
            details?: components["schemas"]["ConsultationDetailsV1Dto"] | components["schemas"]["EvolutionDetailsV1Dto"] | components["schemas"]["LabResultDetailsV1Dto"] | components["schemas"]["PrescriptionDetailsV1Dto"] | components["schemas"]["ProcedureDetailsV1Dto"] | components["schemas"]["TherapyNoteDetailsV1Dto"] | components["schemas"]["OtherDetailsV1Dto"];
            /** @description Referencias a imágenes temporales privadas del actor. */
            attachments?: components["schemas"]["RecordAttachmentInputDto"][];
        };
        UpsertRecordDraftDto: {
            /** @description Obligatorio al actualizar un borrador existente; debe coincidir con su versión. */
            expectedVersion?: number;
            payload: components["schemas"]["RecordDraftPayloadDto"];
        };
        CorrectRecordDto: {
            /** @description Versión vigente del registro que se corrige. */
            expectedVersion: number;
            /** @enum {string} */
            recordType?: "CONSULTATION" | "LAB_RESULT" | "PRESCRIPTION" | "THERAPY_NOTE" | "EVOLUTION" | "PROCEDURE" | "OTHER";
            /**
             * Format: date-time
             * @description Nuevo instante ISO 8601 con zona horaria; hereda el original si se omite
             * @example 2026-09-02T09:30:00-05:00
             */
            attendedAt?: string;
            summary?: string;
            notes?: Record<string, never> | null;
            /** Format: uuid */
            professionalId?: string | null;
            doctorName?: Record<string, never> | null;
            professionalLicense?: Record<string, never> | null;
            service?: Record<string, never> | null;
            preliminaryDiagnosis?: Record<string, never> | null;
            plan?: Record<string, never> | null;
            /** @enum {string} */
            priority?: "URGENT" | "PRIORITY" | "NORMAL" | "ELECTIVE";
            /** @enum {number} */
            schemaVersion?: 1;
            /** @description El esquema concreto se discrimina mediante recordType; versión soportada: 1. */
            details?: components["schemas"]["ConsultationDetailsV1Dto"] | components["schemas"]["EvolutionDetailsV1Dto"] | components["schemas"]["LabResultDetailsV1Dto"] | components["schemas"]["PrescriptionDetailsV1Dto"] | components["schemas"]["ProcedureDetailsV1Dto"] | components["schemas"]["TherapyNoteDetailsV1Dto"] | components["schemas"]["OtherDetailsV1Dto"];
            /** @description Si se omite, hereda los adjuntos del registro original. */
            attachments?: components["schemas"]["RecordAttachmentInputDto"][];
        };
        VoidRecordDto: {
            /** @description Versión vigente del registro que se anula. */
            expectedVersion: number;
            /** @description Motivo de anulación */
            reason: string;
        };
        ValidationChecklistSnapshotItemDto: {
            id: string;
            title: string;
            statement: string;
        };
        ValidationChecklistSnapshotDto: {
            /** @example 1 */
            schemaVersion: number;
            /** @example es-PE */
            locale: string;
            items: components["schemas"]["ValidationChecklistSnapshotItemDto"][];
        };
        DocumentResponseDto: {
            id: string;
            patientId: string;
            originalName: string;
            mimeType: string;
            sizeBytes: number;
            /** @enum {string} */
            status: "PENDING" | "PROCESSING" | "PROCESSED" | "FAILED" | "VALIDATED" | "REJECTED";
            ocrText?: string | null;
            nerEntities?: {
                /** @enum {string} */
                type?: "DIAGNOSIS" | "SYMPTOM" | "MEDICATION" | "PROCEDURE" | "CLINICAL_DATE" | "OBSERVATION";
                value?: string;
                normalizedValue?: string | null;
                sourceSpan?: {
                    page?: number;
                    start?: number;
                    end?: number;
                } | null;
                confidence?: number;
            }[] | null;
            correctedText?: string | null;
            correctedEntities?: {
                /** @enum {string} */
                type?: "DIAGNOSIS" | "SYMPTOM" | "MEDICATION" | "PROCEDURE" | "CLINICAL_DATE" | "OBSERVATION";
                value?: string;
                normalizedValue?: string | null;
            }[] | null;
            correctedAt?: string | null;
            correctedById?: string | null;
            rejectReason?: string | null;
            /** @description Métricas de calidad OCR/NER del servicio IA v2 */
            metrics?: {
                cer?: number | null;
                wer?: number | null;
                charAccuracy?: number | null;
                nerPrecision?: number | null;
                nerRecall?: number | null;
                nerF1?: number | null;
                estimated?: boolean;
            } | null;
            ocrConfidence?: number | null;
            /** @enum {string|null} */
            confidenceLevel?: "HIGH" | "MEDIUM" | "LOW" | null;
            /** Format: date-time */
            createdAt: string;
            createdBy?: string | null;
            processedAt?: string | null;
            reviewedAt?: string | null;
            reviewedBy?: string | null;
            /** @description Copia versionada de las afirmaciones aceptadas al validar. */
            validationChecklist?: components["schemas"]["ValidationChecklistSnapshotDto"] | null;
            validationAttested: boolean;
            validationAttestedAt?: string | null;
            /** Format: date-time */
            updatedAt: string;
            version: number;
        };
        CorrectedEntityDto: {
            /** @enum {string} */
            type?: "DIAGNOSIS" | "SYMPTOM" | "MEDICATION" | "PROCEDURE" | "CLINICAL_DATE" | "OBSERVATION";
            value?: string;
            normalizedValue?: Record<string, never> | null;
        };
        ValidateDocumentDto: {
            /** @description Versión leída por el cliente. La validación falla con 409 si cambió. */
            expectedVersion: number;
            /** @description Texto final revisado. Se guarda junto con la validación sin sobrescribir el OCR. */
            correctedText: string;
            correctedEntities: components["schemas"]["CorrectedEntityDto"][];
            /** @description Identificadores de las confirmaciones clínicas aceptadas por el revisor. El servidor conserva una copia versionada de sus textos. */
            checklistItems: ("text" | "entities" | "sections" | "phi")[];
            /**
             * @description Atestación explícita de que el revisor verificó todos los puntos.
             * @example true
             */
            attested: boolean;
        };
        CorrectDocumentDto: {
            /** @description Versión leída por el cliente. Evita sobrescribir cambios de otro revisor. */
            expectedVersion: number;
            /** @description Texto corregido por el revisor. No sobrescribe el OCR original. */
            correctedText?: string;
            correctedEntities?: components["schemas"]["CorrectedEntityDto"][];
        };
        RejectDocumentDto: {
            /** @description Versión leída por el cliente. Evita rechazar una revisión que ya cambió. */
            expectedVersion: number;
            /** @description Motivo del rechazo */
            reason: string;
        };
        ReviewPatientSummaryDto: {
            id: string;
            firstName: string;
            lastName: string;
            documentType: string;
            documentNumber: string;
        };
        ReviewQueueItemDto: {
            id: string;
            originalName: string;
            mimeType: string;
            sizeBytes: number;
            processedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            patient: components["schemas"]["ReviewPatientSummaryDto"];
        };
        ReviewQueuePageDto: {
            data: components["schemas"]["ReviewQueueItemDto"][];
            total: number;
            page: number;
            limit: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuditController_findMany: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                action?: string;
                outcome?: "SUCCESS" | "DENIED" | "FAILED";
                actorId?: string;
                patientId?: string;
                resourceType?: string;
                resourceId?: string;
                requestId?: string;
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventsPageDto"];
                };
            };
            /** @description Token de acceso ausente, inválido o revocado. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Requiere admin.audit.read. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"][];
                };
            };
        };
    };
    UsersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            /** @description Usuario creado correctamente. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description El email ya está registrado en el sistema. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_searchProfessionals: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description Usuario no encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description Usuario no encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description Usuario no encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_assignRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignRoleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description Usuario o rol no encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description Access token inválido o revocado. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    /** @description clinicview_refresh_token HttpOnly */
                    "Set-Cookie"?: unknown;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponseDto"];
                };
            };
            /** @description Credenciales inválidas. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description clinicview_refresh_token HttpOnly rotada */
                    "Set-Cookie"?: unknown;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponseDto"];
                };
            };
            /** @description Refresh token inválido, expirado o revocado. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesión cerrada de forma idempotente. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleResponseDto"][];
                };
            };
        };
    };
    RolesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleResponseDto"];
                };
            };
            /** @description Rol no encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PatientsController_findAll: {
        parameters: {
            query?: {
                /** @description Texto libre — busca en nombre y número de documento */
                search?: string;
                documentType?: "DNI" | "CE" | "PAS" | "OTHER";
                documentNumber?: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PatientsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePatientDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientResponseDto"];
                };
            };
            /** @description Ya existe un paciente con ese tipo y número de documento. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PatientsController_getCurrentRegistrationDraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientRegistrationDraftResponseDto"];
                };
            };
            /** @description No existe un borrador vigente. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PatientsController_upsertCurrentRegistrationDraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertPatientRegistrationDraftDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientRegistrationDraftResponseDto"];
                };
            };
            /** @description El borrador cambió, expiró o fue reemplazado. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PatientsController_deleteCurrentRegistrationDraft: {
        parameters: {
            query: {
                draftId: string;
                expectedVersion: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El borrador cambió o fue reemplazado. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PatientsController_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PatientsController_exportClinicalHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClinicalHistoryExportResponseDto"];
                };
            };
            /** @description Requiere patients.read, records.read y documents.read. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Paciente no encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PatientsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientResponseDto"];
                };
            };
            /** @description Paciente no encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PatientsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePatientDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientResponseDto"];
                };
            };
            /** @description Paciente no encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PatientsController_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientResponseDto"];
                };
            };
            /** @description Paciente no encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PatientsController_activate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientResponseDto"];
                };
            };
            /** @description Paciente no encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClinicalRecordsController_findAll: {
        parameters: {
            query?: {
                recordType?: "CONSULTATION" | "LAB_RESULT" | "PRESCRIPTION" | "THERAPY_NOTE" | "EVOLUTION" | "PROCEDURE" | "OTHER";
                status?: "ACTIVE" | "CORRECTED" | "VOIDED";
                origin?: "MANUAL" | "DIGITIZED";
                /**
                 * @description Desde, inclusivo: YYYY-MM-DD (inicio del día en America/Lima) o ISO 8601 con zona
                 * @example 2026-09-02
                 * @example 2026-09-02T09:30:00-05:00
                 */
                from?: string;
                /**
                 * @description Hasta: YYYY-MM-DD incluye todo el día en America/Lima; un ISO 8601 con zona es inclusivo
                 * @example 2026-09-02
                 * @example 2026-09-02T18:00:00-05:00
                 */
                to?: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClinicalRecordsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRecordDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordResponseDto"];
                };
            };
        };
    };
    ClinicalRecordsController_getCurrentDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Borrador vigente del usuario para el paciente. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordDraftResponseDto"];
                };
            };
            /** @description No existe un borrador vigente. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClinicalRecordsController_upsertCurrentDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertRecordDraftDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordDraftResponseDto"];
                };
            };
        };
    };
    ClinicalRecordsController_deleteCurrentDraft: {
        parameters: {
            query: {
                expectedVersion: number;
            };
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClinicalRecordsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordResponseDto"];
                };
            };
        };
    };
    ClinicalRecordsController_correct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectRecordDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordResponseDto"];
                };
            };
        };
    };
    ClinicalRecordsController_void: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoidRecordDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordResponseDto"];
                };
            };
        };
    };
    ClinicalRecordMediaController_upload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description JPEG o PNG real; máximo 10 MiB y 25 megapíxeles.
                     */
                    file: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClinicalMediaAssetResponseDto"];
                };
            };
            /** @description La imagen supera los límites permitidos. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClinicalRecordMediaController_getMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
                assetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClinicalMediaAssetResponseDto"];
                };
            };
        };
    };
    ClinicalRecordMediaController_deleteTemporary: {
        parameters: {
            query: {
                /** @description Versión vigente del asset temporal. */
                expectedVersion: number;
            };
            header?: never;
            path: {
                patientId: string;
                assetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Versión obsoleta o imagen ya adjunta. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClinicalRecordMediaController_getContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
                assetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    "Cache-Control"?: string;
                    "X-Content-Type-Options"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    DashboardController_getStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token de acceso ausente o inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Requiere patients.read y documents.read; no se entrega una respuesta parcial. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MedicalDocumentsController_findAll: {
        parameters: {
            query?: {
                status?: "PENDING" | "PROCESSING" | "PROCESSED" | "FAILED" | "VALIDATED" | "REJECTED";
                page?: number;
                limit?: number;
            };
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MedicalDocumentsController_upload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponseDto"];
                };
            };
        };
    };
    MedicalDocumentsController_search: {
        parameters: {
            query: {
                /** @description Palabra clave a buscar en el texto OCR/corregido */
                q: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path: {
                patientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MedicalDocumentsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponseDto"];
                };
            };
        };
    };
    MedicalDocumentsController_downloadFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MedicalDocumentsController_process: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponseDto"];
                };
            };
        };
    };
    MedicalDocumentsController_validate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateDocumentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponseDto"];
                };
            };
            /** @description El estado o la versión cambiaron durante la revisión. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MedicalDocumentsController_saveCorrection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectDocumentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponseDto"];
                };
            };
            /** @description El estado o la versión cambiaron durante la corrección. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MedicalDocumentsController_reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patientId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectDocumentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponseDto"];
                };
            };
            /** @description El estado o la versión cambiaron durante la revisión. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationsController_markAllRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    NotificationsController_markRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReviewController_getQueue: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewQueuePageDto"];
                };
            };
        };
    };
}
